-- =============================================
-- MIGRATION: v27 - Hybrid Inverters & Savings on Configurations
-- Ejecutar en el SQL Editor de Supabase
-- =============================================

-- 1. Add gross savings fields to configuraciones_tecnicas
--    This represents the gross savings generated by the installed technical solution,
--    independent of the financing vehicle chosen.
--    Net savings (affected by financing) remain on opciones_financiamiento.
ALTER TABLE public.configuraciones_tecnicas
ADD COLUMN IF NOT EXISTS ahorro_estimado_mensual NUMERIC,
ADD COLUMN IF NOT EXISTS ahorro_moneda TEXT DEFAULT 'MXN';

COMMENT ON COLUMN public.configuraciones_tecnicas.ahorro_estimado_mensual IS 'Ahorro bruto estimado mensual generado por la solución técnica instalada';
COMMENT ON COLUMN public.configuraciones_tecnicas.ahorro_moneda IS 'Moneda del ahorro bruto estimado (MXN o USD)';

-- Note: Hybrid inverter data (inversores_hibridos: true/false) is stored
-- in the BESS product's datos JSONB column in proyecto_sitio_productos.
-- No additional relational column is needed.
